// src/admin/strings.ts — text for the admin dashboard (/admin).
import { Language } from '../types';

const en = {
  dashboard: 'Admin Dashboard',
  navOverview: 'Overview',
  navMezmur: 'Mezmur',
  navFilms: 'Spiritual Films',
  navUsers: 'Users',
  navComments: 'Comments',
  navSettings: 'Settings',
  backToSite: 'View public site',
  signOut: 'Sign out',

  signInTitle: 'Admin sign in',
  signInSubtitle: 'Sign in with an administrator account to manage ZemaHub.',
  email: 'Email',
  password: 'Password',
  signIn: 'Sign in',
  pleaseWait: 'Please wait...',
  accessDenied: 'Access denied',
  accessDeniedDesc: 'Your account is not an administrator. Ask an existing admin to give you access.',
  useOtherAccount: 'Use another account',
  loading: 'Loading dashboard...',

  statMezmurs: 'Mezmurs',
  statFilms: 'Films',
  statUsers: 'Users',
  statComments: 'Comments',
  statViews: 'Total views',
  statShares: 'Total shares',
  recentComments: 'Latest comments',
  newestUsers: 'Newest users',
  topViewed: 'Most viewed',
  viewAll: 'View all',
  nothingYet: 'Nothing yet.',

  search: 'Search by title, singer or ID...',
  allCategories: 'All categories',
  featuredOnly: 'Featured only',
  addMezmur: 'Add mezmur',
  addFilm: 'Add film',
  colTitle: 'Title',
  colSinger: 'Singer / choir',
  colProducer: 'Producer / channel',
  colCategory: 'Category',
  colYear: 'Year',
  colViews: 'Views',
  colShares: 'Shares',
  colActions: '',
  edit: 'Edit',
  delete: 'Delete',
  openOnSite: 'Open on site',
  confirmDelete: (title: string) => `Delete "${title}"? Its comments will be deleted too. This cannot be undone.`,
  noMatches: 'No items match your filters.',
  results: (n: number) => `${n} item${n === 1 ? '' : 's'}`,

  editMezmur: 'Edit mezmur',
  editFilm: 'Edit film',
  newMezmur: 'New mezmur',
  newFilm: 'New film',
  youtubeLink: 'YouTube link or video ID',
  youtubeHint: 'Paste the full YouTube link — the video ID is extracted automatically.',
  titleAm: 'Title (Amharic)',
  titleEn: 'Title (English)',
  singerAm: 'Singer / choir (Amharic)',
  singerEn: 'Singer / choir (English)',
  producerAm: 'Producer (Amharic)',
  producerEn: 'Producer (English)',
  actors: 'Actors (comma-separated)',
  category: 'Category',
  language: 'Language',
  year: 'Year',
  duration: 'Duration',
  sourceChannel: 'Source YouTube channel',
  descAm: 'Description (Amharic)',
  descEn: 'Description (English)',
  lyrics: 'Lyrics (optional — only real, verified lyrics)',
  featured: 'Featured on the home page',
  save: 'Save',
  create: 'Create',
  cancel: 'Cancel',
  required: 'Amharic title and a YouTube link are required.',
  savedOk: 'Saved.',
  deletedOk: 'Deleted.',

  settingsCatalog: 'Catalog',
  resetTitle: 'Restore the built-in catalog',
  resetDesc:
    'Replaces all mezmurs and films with the built-in catalog. Items added or edited here will be lost; users and comments are kept.',
  resetButton: 'Restore built-in catalog',
  resetConfirm: 'Restore the built-in catalog? Items you added or edited will be lost.',
  resetDone: 'Catalog restored.',
  settingsLinks: 'Links',
  privacyPolicy: 'Privacy policy',
  language_: 'Dashboard language'
};

const am: typeof en = {
  dashboard: 'የአስተዳዳሪ ዳሽቦርድ',
  navOverview: 'አጠቃላይ እይታ',
  navMezmur: 'መዝሙራት',
  navFilms: 'መንፈሳዊ ፊልሞች',
  navUsers: 'ተጠቃሚዎች',
  navComments: 'አስተያየቶች',
  navSettings: 'ቅንብሮች',
  backToSite: 'ወደ ድረ ገጹ',
  signOut: 'ውጣ',

  signInTitle: 'የአስተዳዳሪ መግቢያ',
  signInSubtitle: 'ዜማሀብን ለማስተዳደር በአስተዳዳሪ መለያ ይግቡ።',
  email: 'ኢሜይል',
  password: 'የይለፍ ቃል',
  signIn: 'ግባ',
  pleaseWait: 'እባክዎ ይጠብቁ...',
  accessDenied: 'መግባት አይፈቀድም',
  accessDeniedDesc: 'መለያዎ አስተዳዳሪ አይደለም። ያለ አስተዳዳሪ ፈቃድ እንዲሰጥዎ ይጠይቁ።',
  useOtherAccount: 'በሌላ መለያ ይግቡ',
  loading: 'ዳሽቦርዱ በመጫን ላይ...',

  statMezmurs: 'መዝሙራት',
  statFilms: 'ፊልሞች',
  statUsers: 'ተጠቃሚዎች',
  statComments: 'አስተያየቶች',
  statViews: 'ጠቅላላ ዕይታ',
  statShares: 'ጠቅላላ ማጋራት',
  recentComments: 'የቅርብ ጊዜ አስተያየቶች',
  newestUsers: 'አዲስ ተጠቃሚዎች',
  topViewed: 'በብዛት የታዩ',
  viewAll: 'ሁሉንም ይዩ',
  nothingYet: 'እስካሁን ምንም የለም።',

  search: 'በርዕስ፣ በዘማሪ ወይም በመለያ ቁጥር ይፈልጉ...',
  allCategories: 'ሁሉም ምድቦች',
  featuredOnly: 'የተመረጡ ብቻ',
  addMezmur: 'መዝሙር ጨምር',
  addFilm: 'ፊልም ጨምር',
  colTitle: 'ርዕስ',
  colSinger: 'ዘማሪ / መዘምራን',
  colProducer: 'አዘጋጅ / ቻናል',
  colCategory: 'ምድብ',
  colYear: 'ዓመት',
  colViews: 'ዕይታ',
  colShares: 'ማጋራት',
  colActions: '',
  edit: 'አስተካክል',
  delete: 'አጥፋ',
  openOnSite: 'በድረ ገጹ ክፈት',
  confirmDelete: (title: string) => `"${title}" ይጥፋ? አስተያየቶቹም አብረው ይጠፋሉ። ይህ ሊመለስ አይችልም።`,
  noMatches: 'ከማጣሪያዎ ጋር የሚስማማ የለም።',
  results: (n: number) => `${n} ንጥሎች`,

  editMezmur: 'መዝሙር አስተካክል',
  editFilm: 'ፊልም አስተካክል',
  newMezmur: 'አዲስ መዝሙር',
  newFilm: 'አዲስ ፊልም',
  youtubeLink: 'የዩቲዩብ ሊንክ ወይም የቪዲዮ መለያ',
  youtubeHint: 'ሙሉውን የዩቲዩብ ሊንክ ይለጥፉ — የቪዲዮ መለያው በራሱ ይወጣል።',
  titleAm: 'ርዕስ (በአማርኛ)',
  titleEn: 'ርዕስ (በእንግሊዝኛ)',
  singerAm: 'ዘማሪ / መዘምራን (በአማርኛ)',
  singerEn: 'ዘማሪ / መዘምራን (በእንግሊዝኛ)',
  producerAm: 'አዘጋጅ (በአማርኛ)',
  producerEn: 'አዘጋጅ (በእንግሊዝኛ)',
  actors: 'ተዋንያን (በኮማ የተለዩ)',
  category: 'ምድብ',
  language: 'ቋንቋ',
  year: 'ዓመት',
  duration: 'ርዝመት',
  sourceChannel: 'ምንጭ የዩቲዩብ ቻናል',
  descAm: 'ማብራሪያ (በአማርኛ)',
  descEn: 'ማብራሪያ (በእንግሊዝኛ)',
  lyrics: 'ግጥም (አማራጭ — ትክክለኛ ግጥም ብቻ)',
  featured: 'በመነሻ ገጽ ላይ ይመረጥ',
  save: 'አስቀምጥ',
  create: 'ፍጠር',
  cancel: 'ተው',
  required: 'የአማርኛ ርዕስና የዩቲዩብ ሊንክ ያስፈልጋሉ።',
  savedOk: 'ተቀምጧል።',
  deletedOk: 'ጠፍቷል።',

  settingsCatalog: 'ካታሎግ',
  resetTitle: 'ዋናውን ካታሎግ መልስ',
  resetDesc: 'ሁሉንም መዝሙራትና ፊልሞች በዋናው ካታሎግ ይተካል። እዚህ የተጨመሩ ወይም የተስተካከሉ ይጠፋሉ፤ ተጠቃሚዎችና አስተያየቶች ይቀራሉ።',
  resetButton: 'ዋናውን ካታሎግ መልስ',
  resetConfirm: 'ዋናውን ካታሎግ ልመልስ? የጨመሯቸው ወይም ያስተካከሏቸው ይጠፋሉ።',
  resetDone: 'ካታሎጉ ተመልሷል።',
  settingsLinks: 'ሊንኮች',
  privacyPolicy: 'የግላዊነት ፖሊሲ',
  language_: 'የዳሽቦርድ ቋንቋ'
};

export const adminStrings: Record<Language, typeof en> = { en, am };
export type AdminStrings = typeof en;
